<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>myblog – finalproject</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">myblog</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">



<p>Kaitlyn Coons 12 March 2023</p>
<section id="the-healthcare-system-a-comparative-analysis" class="level1">
<h1>The Healthcare System: A Comparative Analysis</h1>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p><strong>The Project</strong></p>
<p>This project is based on the Hospital Dataset from the <a href="https://corgis-edu.github.io/corgis/csv/hospitals/">The Collection of Really Great, Interesting, Situated Datasets (CORGIS)</a>. The dataset includes information on the names, locations, average ratings, mortality rates, and average procedure costs, among other variables.</p>
<p>To better understand the varying experiences with healthcare across the Unites States, this project compares the quality and cost of medical procedures of hospitals in California and Wyoming. While they may appear to be a random pairing of states, California and Wyoming were chosen because of their designation as the most populous (CA) and least populous (WY) states.</p>
<p><strong>Context and Motivation</strong></p>
<p>Access to healthcare in the United States is not a new issue, but it has been recently stressed by the COVID-19 pandemic. As asserted by the <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3540621/">National Library of Medicine</a>, there are significant disparities in access to healthcare based on race and ethnicity. Drawing on the CORGIS dataset, this project seeks to discover if other barriers to heathcare exist such as price and quality of medical attention.</p>
<p>I do not have prior experience working with healthcare data, nor am I particularly interested in the world of medicine. That said, the past few years of living through the COVID-19 pandemic have sparked my interest in uncovering the disparities felt within the healthcare system.</p>
<p><strong>Key Terms</strong></p>
<p>The dataset divides U.S. hospitals into three categories: government, private, and proprietary. Government hospitals are those –as the name suggest– that are owned and funded by the government. They are public entities and operate off of money collected for taxes. Private hospitals are not affiliated with the government, instead run by corporations. They can be book non-profit and for-profit. Lastly, proprietary hospitals are for-profit institutions also run by individual corporations or specific government entities.</p>
<p><strong>Preliminary Research Questions</strong> 1. Is there a correlation between medical costs and the quality of treatment?</p>
<ol start="2" type="1">
<li>Does the type of hospital (government, private, or proprietary) impact medical costs and the quality of treatment?</li>
</ol>
<p><strong>Data Exploration</strong></p>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-scrolled="true" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>hospital_df <span class="op">=</span> pd.read_csv(<span class="st">'https://corgis-edu.github.io/corgis/datasets/csv/hospitals/hospitals.csv'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>hospital_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Facility.Name</th>
      <th>Facility.City</th>
      <th>Facility.State</th>
      <th>Facility.Type</th>
      <th>Rating.Overall</th>
      <th>Rating.Mortality</th>
      <th>Rating.Safety</th>
      <th>Rating.Readmission</th>
      <th>Rating.Experience</th>
      <th>Rating.Effectiveness</th>
      <th>...</th>
      <th>Procedure.Heart Attack.Value</th>
      <th>Procedure.Heart Failure.Cost</th>
      <th>Procedure.Heart Failure.Quality</th>
      <th>Procedure.Heart Failure.Value</th>
      <th>Procedure.Pneumonia.Cost</th>
      <th>Procedure.Pneumonia.Quality</th>
      <th>Procedure.Pneumonia.Value</th>
      <th>Procedure.Hip Knee.Cost</th>
      <th>Procedure.Hip Knee.Quality</th>
      <th>Procedure.Hip Knee.Value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Southeast Alabama Medical Center</td>
      <td>Dothan</td>
      <td>AL</td>
      <td>Government</td>
      <td>2</td>
      <td>Below</td>
      <td>Above</td>
      <td>Below</td>
      <td>Below</td>
      <td>Same</td>
      <td>...</td>
      <td>Average</td>
      <td>17041</td>
      <td>Average</td>
      <td>Average</td>
      <td>18281</td>
      <td>Average</td>
      <td>Average</td>
      <td>25812</td>
      <td>Average</td>
      <td>Higher</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Marshall Medical Center South</td>
      <td>Boaz</td>
      <td>AL</td>
      <td>Government</td>
      <td>1</td>
      <td>Below</td>
      <td>Below</td>
      <td>Below</td>
      <td>Same</td>
      <td>Above</td>
      <td>...</td>
      <td>Average</td>
      <td>15819</td>
      <td>Worse</td>
      <td>Average</td>
      <td>15614</td>
      <td>Worse</td>
      <td>Lower</td>
      <td>22747</td>
      <td>Average</td>
      <td>Average</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Eliza Coffee Memorial Hospital</td>
      <td>Florence</td>
      <td>AL</td>
      <td>Government</td>
      <td>3</td>
      <td>Below</td>
      <td>Above</td>
      <td>Above</td>
      <td>Below</td>
      <td>Same</td>
      <td>...</td>
      <td>Average</td>
      <td>16334</td>
      <td>Average</td>
      <td>Average</td>
      <td>17371</td>
      <td>Average</td>
      <td>Average</td>
      <td>24491</td>
      <td>Average</td>
      <td>Higher</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Mizell Memorial Hospital</td>
      <td>Opp</td>
      <td>AL</td>
      <td>Private</td>
      <td>1</td>
      <td>Same</td>
      <td>Same</td>
      <td>Below</td>
      <td>Below</td>
      <td>Below</td>
      <td>...</td>
      <td>Unknown</td>
      <td>14541</td>
      <td>Average</td>
      <td>Lower</td>
      <td>15226</td>
      <td>Worse</td>
      <td>Lower</td>
      <td>23472</td>
      <td>Average</td>
      <td>Average</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Crenshaw Community Hospital</td>
      <td>Luverne</td>
      <td>AL</td>
      <td>Proprietary</td>
      <td>4</td>
      <td>Same</td>
      <td>None</td>
      <td>Above</td>
      <td>None</td>
      <td>Same</td>
      <td>...</td>
      <td>Unknown</td>
      <td>13767</td>
      <td>Average</td>
      <td>Lower</td>
      <td>14341</td>
      <td>Average</td>
      <td>Lower</td>
      <td>0</td>
      <td>Unknown</td>
      <td>Unknown</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>4767</th>
      <td>Providence Hospital Of North Houston Llc</td>
      <td>Houston</td>
      <td>TX</td>
      <td>Proprietary</td>
      <td>-1</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>...</td>
      <td>Unknown</td>
      <td>0</td>
      <td>Unknown</td>
      <td>Unknown</td>
      <td>0</td>
      <td>Unknown</td>
      <td>Unknown</td>
      <td>0</td>
      <td>Unknown</td>
      <td>Unknown</td>
    </tr>
    <tr>
      <th>4768</th>
      <td>The Hospitals Of Providence Transmountain Campus</td>
      <td>El Paso</td>
      <td>TX</td>
      <td>Proprietary</td>
      <td>-1</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>Same</td>
      <td>Same</td>
      <td>...</td>
      <td>Unknown</td>
      <td>0</td>
      <td>Unknown</td>
      <td>Unknown</td>
      <td>0</td>
      <td>Unknown</td>
      <td>Unknown</td>
      <td>0</td>
      <td>Unknown</td>
      <td>Unknown</td>
    </tr>
    <tr>
      <th>4769</th>
      <td>Saint Camillus Medical Center</td>
      <td>Hurst</td>
      <td>TX</td>
      <td>Proprietary</td>
      <td>-1</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>...</td>
      <td>Unknown</td>
      <td>0</td>
      <td>Unknown</td>
      <td>Unknown</td>
      <td>0</td>
      <td>Unknown</td>
      <td>Unknown</td>
      <td>0</td>
      <td>Unknown</td>
      <td>Unknown</td>
    </tr>
    <tr>
      <th>4770</th>
      <td>Houston Methodist The Woodlands Hospital</td>
      <td>The Woodlands</td>
      <td>TX</td>
      <td>Private</td>
      <td>3</td>
      <td>None</td>
      <td>Same</td>
      <td>None</td>
      <td>Above</td>
      <td>Same</td>
      <td>...</td>
      <td>Unknown</td>
      <td>0</td>
      <td>Unknown</td>
      <td>Unknown</td>
      <td>0</td>
      <td>Unknown</td>
      <td>Unknown</td>
      <td>0</td>
      <td>Unknown</td>
      <td>Unknown</td>
    </tr>
    <tr>
      <th>4771</th>
      <td>The Hospitals Of Providence Horizon City Campus</td>
      <td>Horizon City</td>
      <td>TX</td>
      <td>Proprietary</td>
      <td>-1</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>Same</td>
      <td>...</td>
      <td>Unknown</td>
      <td>0</td>
      <td>Unknown</td>
      <td>Unknown</td>
      <td>0</td>
      <td>Unknown</td>
      <td>Unknown</td>
      <td>0</td>
      <td>Unknown</td>
      <td>Unknown</td>
    </tr>
  </tbody>
</table>
<p>4772 rows × 24 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>hospital_df.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Rating.Overall</th>
      <th>Procedure.Heart Attack.Cost</th>
      <th>Procedure.Heart Failure.Cost</th>
      <th>Procedure.Pneumonia.Cost</th>
      <th>Procedure.Hip Knee.Cost</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>4772.000000</td>
      <td>4772.000000</td>
      <td>4772.000000</td>
      <td>4772.000000</td>
      <td>4772.000000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>2.179380</td>
      <td>11360.977997</td>
      <td>12149.034367</td>
      <td>14625.655071</td>
      <td>12501.068525</td>
    </tr>
    <tr>
      <th>std</th>
      <td>1.935582</td>
      <td>11988.404171</td>
      <td>7502.579223</td>
      <td>6598.128266</td>
      <td>10997.181810</td>
    </tr>
    <tr>
      <th>min</th>
      <td>-1.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>1.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>15169.500000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>3.000000</td>
      <td>0.000000</td>
      <td>15921.500000</td>
      <td>16933.500000</td>
      <td>19120.000000</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>4.000000</td>
      <td>23764.250000</td>
      <td>17126.500000</td>
      <td>18245.000000</td>
      <td>21985.500000</td>
    </tr>
    <tr>
      <th>max</th>
      <td>5.000000</td>
      <td>29670.000000</td>
      <td>22450.000000</td>
      <td>27126.000000</td>
      <td>42546.000000</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>hospital_df.sample()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Facility.Name</th>
      <th>Facility.City</th>
      <th>Facility.State</th>
      <th>Facility.Type</th>
      <th>Rating.Overall</th>
      <th>Rating.Mortality</th>
      <th>Rating.Safety</th>
      <th>Rating.Readmission</th>
      <th>Rating.Experience</th>
      <th>Rating.Effectiveness</th>
      <th>...</th>
      <th>Procedure.Heart Attack.Value</th>
      <th>Procedure.Heart Failure.Cost</th>
      <th>Procedure.Heart Failure.Quality</th>
      <th>Procedure.Heart Failure.Value</th>
      <th>Procedure.Pneumonia.Cost</th>
      <th>Procedure.Pneumonia.Quality</th>
      <th>Procedure.Pneumonia.Value</th>
      <th>Procedure.Hip Knee.Cost</th>
      <th>Procedure.Hip Knee.Quality</th>
      <th>Procedure.Hip Knee.Value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>4007</th>
      <td>Memorial Hospital</td>
      <td>Gonzales</td>
      <td>TX</td>
      <td>Government</td>
      <td>4</td>
      <td>None</td>
      <td>None</td>
      <td>Same</td>
      <td>Above</td>
      <td>Same</td>
      <td>...</td>
      <td>Unknown</td>
      <td>15875</td>
      <td>Average</td>
      <td>Average</td>
      <td>16968</td>
      <td>Average</td>
      <td>Average</td>
      <td>0</td>
      <td>Unknown</td>
      <td>Unknown</td>
    </tr>
  </tbody>
</table>
<p>1 rows × 24 columns</p>
</div>
</div>
</div>
<p>It is interesting that the mortality rating, safety rating, readmission rating, and experience rating are based on a comparison to the national averages. While on one hand this limits the credibility of the dataset because the raw numbers are not presented, as it forces the viewer to rely on the creator’s analysis, it also streamlines the dataset. The viewer learns much more about a hospital by reading that it is “Above” the national rating for safety than they would from reading over the equivalent numerical value.</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>hospital_df.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>Index(['Facility.Name', 'Facility.City', 'Facility.State', 'Facility.Type',
       'Rating.Overall', 'Rating.Mortality', 'Rating.Safety',
       'Rating.Readmission', 'Rating.Experience', 'Rating.Effectiveness',
       'Rating.Timeliness', 'Rating.Imaging', 'Procedure.Heart Attack.Cost',
       'Procedure.Heart Attack.Quality', 'Procedure.Heart Attack.Value',
       'Procedure.Heart Failure.Cost', 'Procedure.Heart Failure.Quality',
       'Procedure.Heart Failure.Value', 'Procedure.Pneumonia.Cost',
       'Procedure.Pneumonia.Quality', 'Procedure.Pneumonia.Value',
       'Procedure.Hip Knee.Cost', 'Procedure.Hip Knee.Quality',
       'Procedure.Hip Knee.Value'],
      dtype='object')</code></pre>
</div>
</div>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>hospital_df.describe(include<span class="op">=</span><span class="st">'all'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Facility.Name</th>
      <th>Facility.City</th>
      <th>Facility.State</th>
      <th>Facility.Type</th>
      <th>Rating.Overall</th>
      <th>Rating.Mortality</th>
      <th>Rating.Safety</th>
      <th>Rating.Readmission</th>
      <th>Rating.Experience</th>
      <th>Rating.Effectiveness</th>
      <th>...</th>
      <th>Procedure.Heart Attack.Value</th>
      <th>Procedure.Heart Failure.Cost</th>
      <th>Procedure.Heart Failure.Quality</th>
      <th>Procedure.Heart Failure.Value</th>
      <th>Procedure.Pneumonia.Cost</th>
      <th>Procedure.Pneumonia.Quality</th>
      <th>Procedure.Pneumonia.Value</th>
      <th>Procedure.Hip Knee.Cost</th>
      <th>Procedure.Hip Knee.Quality</th>
      <th>Procedure.Hip Knee.Value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>4772</td>
      <td>4772</td>
      <td>4772</td>
      <td>4772</td>
      <td>4772.000000</td>
      <td>4772</td>
      <td>4772</td>
      <td>4772</td>
      <td>4772</td>
      <td>4772</td>
      <td>...</td>
      <td>4772</td>
      <td>4772.000000</td>
      <td>4772</td>
      <td>4772</td>
      <td>4772.000000</td>
      <td>4772</td>
      <td>4772</td>
      <td>4772.000000</td>
      <td>4772</td>
      <td>4772</td>
    </tr>
    <tr>
      <th>unique</th>
      <td>4589</td>
      <td>2929</td>
      <td>56</td>
      <td>5</td>
      <td>NaN</td>
      <td>4</td>
      <td>4</td>
      <td>4</td>
      <td>4</td>
      <td>4</td>
      <td>...</td>
      <td>4</td>
      <td>NaN</td>
      <td>4</td>
      <td>4</td>
      <td>NaN</td>
      <td>4</td>
      <td>4</td>
      <td>NaN</td>
      <td>4</td>
      <td>4</td>
    </tr>
    <tr>
      <th>top</th>
      <td>Memorial Hospital</td>
      <td>Chicago</td>
      <td>TX</td>
      <td>Private</td>
      <td>NaN</td>
      <td>Same</td>
      <td>None</td>
      <td>Above</td>
      <td>None</td>
      <td>Same</td>
      <td>...</td>
      <td>Unknown</td>
      <td>NaN</td>
      <td>Average</td>
      <td>Average</td>
      <td>NaN</td>
      <td>Average</td>
      <td>Average</td>
      <td>NaN</td>
      <td>Average</td>
      <td>Unknown</td>
    </tr>
    <tr>
      <th>freq</th>
      <td>15</td>
      <td>29</td>
      <td>403</td>
      <td>2078</td>
      <td>NaN</td>
      <td>2663</td>
      <td>2142</td>
      <td>1508</td>
      <td>1340</td>
      <td>3372</td>
      <td>...</td>
      <td>2506</td>
      <td>NaN</td>
      <td>3141</td>
      <td>2522</td>
      <td>NaN</td>
      <td>3555</td>
      <td>2338</td>
      <td>NaN</td>
      <td>2615</td>
      <td>2045</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>2.179380</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>...</td>
      <td>NaN</td>
      <td>12149.034367</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>14625.655071</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>12501.068525</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>std</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1.935582</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>...</td>
      <td>NaN</td>
      <td>7502.579223</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>6598.128266</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>10997.181810</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>min</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>-1.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>...</td>
      <td>NaN</td>
      <td>0.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>0.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>0.000000</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>...</td>
      <td>NaN</td>
      <td>0.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>15169.500000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>0.000000</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>3.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>...</td>
      <td>NaN</td>
      <td>15921.500000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>16933.500000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>19120.000000</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>4.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>...</td>
      <td>NaN</td>
      <td>17126.500000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>18245.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>21985.500000</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>max</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>5.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>...</td>
      <td>NaN</td>
      <td>22450.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>27126.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>42546.000000</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
<p>11 rows × 24 columns</p>
</div>
</div>
</div>
<p>While it is interesting to view a statistical representation of all hospitals across the U.S., it is difficult to make meaningful conclusions with so many entries. Moreover, analyzing individual states will allow the project to conclude whether the quality and cost of healthcare differs across the U.S.</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#extracting data for California</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>CAdf <span class="op">=</span> hospital_df.loc[ hospital_df[<span class="st">'Facility.State'</span>] <span class="op">==</span> <span class="st">'CA'</span> ]</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>CAdf.sample()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Facility.Name</th>
      <th>Facility.City</th>
      <th>Facility.State</th>
      <th>Facility.Type</th>
      <th>Rating.Overall</th>
      <th>Rating.Mortality</th>
      <th>Rating.Safety</th>
      <th>Rating.Readmission</th>
      <th>Rating.Experience</th>
      <th>Rating.Effectiveness</th>
      <th>...</th>
      <th>Procedure.Heart Attack.Value</th>
      <th>Procedure.Heart Failure.Cost</th>
      <th>Procedure.Heart Failure.Quality</th>
      <th>Procedure.Heart Failure.Value</th>
      <th>Procedure.Pneumonia.Cost</th>
      <th>Procedure.Pneumonia.Quality</th>
      <th>Procedure.Pneumonia.Value</th>
      <th>Procedure.Hip Knee.Cost</th>
      <th>Procedure.Hip Knee.Quality</th>
      <th>Procedure.Hip Knee.Value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>553</th>
      <td>College Medical Center</td>
      <td>Long Beach</td>
      <td>CA</td>
      <td>Proprietary</td>
      <td>3</td>
      <td>None</td>
      <td>Above</td>
      <td>Below</td>
      <td>None</td>
      <td>Same</td>
      <td>...</td>
      <td>Unknown</td>
      <td>17321</td>
      <td>Unknown</td>
      <td>Unknown</td>
      <td>22113</td>
      <td>Average</td>
      <td>Higher</td>
      <td>0</td>
      <td>Unknown</td>
      <td>Unknown</td>
    </tr>
  </tbody>
</table>
<p>1 rows × 24 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>CAdf.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Rating.Overall</th>
      <th>Procedure.Heart Attack.Cost</th>
      <th>Procedure.Heart Failure.Cost</th>
      <th>Procedure.Pneumonia.Cost</th>
      <th>Procedure.Hip Knee.Cost</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>340.000000</td>
      <td>340.000000</td>
      <td>340.000000</td>
      <td>340.000000</td>
      <td>340.000000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>2.364706</td>
      <td>14079.597059</td>
      <td>12567.961765</td>
      <td>15012.900000</td>
      <td>12629.926471</td>
    </tr>
    <tr>
      <th>std</th>
      <td>1.633694</td>
      <td>12074.532434</td>
      <td>7660.121412</td>
      <td>7382.317522</td>
      <td>10915.032397</td>
    </tr>
    <tr>
      <th>min</th>
      <td>-1.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>2.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>15549.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>3.000000</td>
      <td>22592.500000</td>
      <td>16495.500000</td>
      <td>17407.000000</td>
      <td>19025.000000</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>3.000000</td>
      <td>24561.500000</td>
      <td>17655.250000</td>
      <td>19089.250000</td>
      <td>21639.750000</td>
    </tr>
    <tr>
      <th>max</th>
      <td>5.000000</td>
      <td>29606.000000</td>
      <td>21799.000000</td>
      <td>26819.000000</td>
      <td>30424.000000</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#extracting data for Wyoming</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>WYdf <span class="op">=</span> hospital_df.loc[ hospital_df[<span class="st">'Facility.State'</span>] <span class="op">==</span> <span class="st">'WY'</span> ]</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>WYdf.sample()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Facility.Name</th>
      <th>Facility.City</th>
      <th>Facility.State</th>
      <th>Facility.Type</th>
      <th>Rating.Overall</th>
      <th>Rating.Mortality</th>
      <th>Rating.Safety</th>
      <th>Rating.Readmission</th>
      <th>Rating.Experience</th>
      <th>Rating.Effectiveness</th>
      <th>...</th>
      <th>Procedure.Heart Attack.Value</th>
      <th>Procedure.Heart Failure.Cost</th>
      <th>Procedure.Heart Failure.Quality</th>
      <th>Procedure.Heart Failure.Value</th>
      <th>Procedure.Pneumonia.Cost</th>
      <th>Procedure.Pneumonia.Quality</th>
      <th>Procedure.Pneumonia.Value</th>
      <th>Procedure.Hip Knee.Cost</th>
      <th>Procedure.Hip Knee.Quality</th>
      <th>Procedure.Hip Knee.Value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>4680</th>
      <td>Cheyenne Regional Medical Center</td>
      <td>Cheyenne</td>
      <td>WY</td>
      <td>Unknown</td>
      <td>3</td>
      <td>Same</td>
      <td>Below</td>
      <td>Same</td>
      <td>Below</td>
      <td>Same</td>
      <td>...</td>
      <td>Average</td>
      <td>15548</td>
      <td>Average</td>
      <td>Average</td>
      <td>17293</td>
      <td>Average</td>
      <td>Average</td>
      <td>20529</td>
      <td>Average</td>
      <td>Lower</td>
    </tr>
  </tbody>
</table>
<p>1 rows × 24 columns</p>
</div>
</div>
</div>
<div class="cell" data-scrolled="true" data-execution_count="11">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>WYdf.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Rating.Overall</th>
      <th>Procedure.Heart Attack.Cost</th>
      <th>Procedure.Heart Failure.Cost</th>
      <th>Procedure.Pneumonia.Cost</th>
      <th>Procedure.Hip Knee.Cost</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>28.000000</td>
      <td>28.000000</td>
      <td>28.000000</td>
      <td>28.000000</td>
      <td>28.000000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>1.785714</td>
      <td>3348.392857</td>
      <td>10061.607143</td>
      <td>10966.285714</td>
      <td>10324.821429</td>
    </tr>
    <tr>
      <th>std</th>
      <td>2.200289</td>
      <td>8366.675013</td>
      <td>7703.980675</td>
      <td>7181.859719</td>
      <td>10601.491960</td>
    </tr>
    <tr>
      <th>min</th>
      <td>-1.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>-1.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>3.000000</td>
      <td>0.000000</td>
      <td>14711.000000</td>
      <td>14957.000000</td>
      <td>9077.000000</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>3.250000</td>
      <td>0.000000</td>
      <td>15902.750000</td>
      <td>15693.000000</td>
      <td>20280.750000</td>
    </tr>
    <tr>
      <th>max</th>
      <td>5.000000</td>
      <td>24962.000000</td>
      <td>18649.000000</td>
      <td>18352.000000</td>
      <td>23892.000000</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>A cursory glance at the mean cost of a heart attack procedure indicates drastic differences in the pricing of medical procedures between the states. While the mean cost in California is roughly 14079.60 (14079.597059), the mean cost in Wyoming is roughly 3348.39 (3348.392857) U.S. dollars.</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#number of Government hospitals in the U.S.</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>UStypeGt <span class="op">=</span> hospital_df.loc[ hospital_df[<span class="st">'Facility.Type'</span>] <span class="op">==</span> <span class="st">'Government'</span> ]</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>UStypeGt.shape</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co">#number of Private hospitals in the U.S.</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>UStypePri <span class="op">=</span> hospital_df.loc[ hospital_df[<span class="st">'Facility.Type'</span>] <span class="op">==</span> <span class="st">'Private'</span> ]</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>UStypePri.shape</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="co">#number of Proprietary in the U.S.</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>UStypePro <span class="op">=</span> hospital_df.loc[ hospital_df[<span class="st">'Facility.Type'</span>] <span class="op">==</span> <span class="st">'Proprietary'</span> ]</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>UStypePro.shape</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'US Government hospitals ='</span>, UStypeGt.shape) </span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'US Private hospitals ='</span> ,UStypePri.shape) </span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'US Proprietary hospitals ='</span>, UStypePro.shape)</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>USx <span class="op">=</span> (<span class="st">'Government'</span>, <span class="st">'Private'</span>, <span class="st">'Proprietary'</span>)</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>USy <span class="op">=</span> (<span class="dv">1064</span>, <span class="dv">2078</span>, <span class="dv">796</span>)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>plt.bar(USx, USy, color <span class="op">=</span> <span class="st">'purple'</span>)</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Type of Hospital"</span>, size<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Count of Hospitals"</span>,size<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Variety of Hospitals in the U.S."</span>,size<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a><span class="co">#number of Government hospitals in CA</span></span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>CAtypeGt <span class="op">=</span> CAdf.loc[ CAdf[<span class="st">'Facility.Type'</span>] <span class="op">==</span> <span class="st">'Government'</span> ]</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>CAtypeGt.shape</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a><span class="co">#number of Private hospitals in CA</span></span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>CAtypePri <span class="op">=</span> CAdf.loc[ CAdf[<span class="st">'Facility.Type'</span>] <span class="op">==</span> <span class="st">'Private'</span> ]</span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>CAtypePri.shape</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a><span class="co">#number of Proprietary in CA</span></span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a>CAtypePro <span class="op">=</span> CAdf.loc[ CAdf[<span class="st">'Facility.Type'</span>] <span class="op">==</span> <span class="st">'Proprietary'</span> ]</span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>CAtypePro.shape</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA Government hospitals ='</span>, CAtypeGt.shape) </span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA Private hospitals ='</span> ,CAtypePri.shape) </span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA Proprietary hospitals ='</span>, CAtypePro.shape)</span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-42"><a href="#cb12-42" aria-hidden="true" tabindex="-1"></a>CAx <span class="op">=</span> (<span class="st">'Government'</span>, <span class="st">'Private'</span>, <span class="st">'Proprietary'</span>)</span>
<span id="cb12-43"><a href="#cb12-43" aria-hidden="true" tabindex="-1"></a>CAy <span class="op">=</span> (<span class="dv">64</span>, <span class="dv">105</span>, <span class="dv">76</span>)</span>
<span id="cb12-44"><a href="#cb12-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-45"><a href="#cb12-45" aria-hidden="true" tabindex="-1"></a>plt.bar(CAx, CAy, color <span class="op">=</span> <span class="st">'darkorange'</span>)</span>
<span id="cb12-46"><a href="#cb12-46" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Type of Hospital"</span>, size<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb12-47"><a href="#cb12-47" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Count of Hospitals"</span>,size<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb12-48"><a href="#cb12-48" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Variety of Hospitals in California"</span>,size<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb12-49"><a href="#cb12-49" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb12-50"><a href="#cb12-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-51"><a href="#cb12-51" aria-hidden="true" tabindex="-1"></a><span class="co">#number of Government hospitals in WY</span></span>
<span id="cb12-52"><a href="#cb12-52" aria-hidden="true" tabindex="-1"></a>WYtypeGt <span class="op">=</span> WYdf.loc[ WYdf[<span class="st">'Facility.Type'</span>] <span class="op">==</span> <span class="st">'Government'</span> ]</span>
<span id="cb12-53"><a href="#cb12-53" aria-hidden="true" tabindex="-1"></a>WYtypeGt.shape</span>
<span id="cb12-54"><a href="#cb12-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-55"><a href="#cb12-55" aria-hidden="true" tabindex="-1"></a><span class="co">#number of Private hospitals in WY</span></span>
<span id="cb12-56"><a href="#cb12-56" aria-hidden="true" tabindex="-1"></a>WYtypePri <span class="op">=</span> WYdf.loc[ WYdf[<span class="st">'Facility.Type'</span>] <span class="op">==</span> <span class="st">'Private'</span> ]</span>
<span id="cb12-57"><a href="#cb12-57" aria-hidden="true" tabindex="-1"></a>WYtypePri.shape</span>
<span id="cb12-58"><a href="#cb12-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-59"><a href="#cb12-59" aria-hidden="true" tabindex="-1"></a><span class="co">#number of Proprietary in WY</span></span>
<span id="cb12-60"><a href="#cb12-60" aria-hidden="true" tabindex="-1"></a>WYtypePro <span class="op">=</span> WYdf.loc[ WYdf[<span class="st">'Facility.Type'</span>] <span class="op">==</span> <span class="st">'Proprietary'</span> ]</span>
<span id="cb12-61"><a href="#cb12-61" aria-hidden="true" tabindex="-1"></a>WYtypePro.shape</span>
<span id="cb12-62"><a href="#cb12-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-63"><a href="#cb12-63" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY Government hospitals ='</span>, WYtypeGt.shape) </span>
<span id="cb12-64"><a href="#cb12-64" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY Private hospitals ='</span> ,WYtypePri.shape) </span>
<span id="cb12-65"><a href="#cb12-65" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY Proprietary hospitals ='</span>, WYtypePro.shape)</span>
<span id="cb12-66"><a href="#cb12-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-67"><a href="#cb12-67" aria-hidden="true" tabindex="-1"></a>WYx <span class="op">=</span> (<span class="st">'Government'</span>, <span class="st">'Private'</span>, <span class="st">'Proprietary'</span>)</span>
<span id="cb12-68"><a href="#cb12-68" aria-hidden="true" tabindex="-1"></a>WYy <span class="op">=</span> (<span class="dv">21</span>, <span class="dv">1</span>, <span class="dv">4</span>)</span>
<span id="cb12-69"><a href="#cb12-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-70"><a href="#cb12-70" aria-hidden="true" tabindex="-1"></a>plt.bar(WYx, WYy, color <span class="op">=</span> <span class="st">'dodgerblue'</span>)</span>
<span id="cb12-71"><a href="#cb12-71" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Type of Hospital"</span>, size<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb12-72"><a href="#cb12-72" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Count of Hospitals"</span>,size<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb12-73"><a href="#cb12-73" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Variety of Hospitals in Wyoming"</span>,size<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb12-74"><a href="#cb12-74" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>US Government hospitals = (1064, 24)
US Private hospitals = (2078, 24)
US Proprietary hospitals = (796, 24)</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-12-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>CA Government hospitals = (64, 24)
CA Private hospitals = (105, 24)
CA Proprietary hospitals = (76, 24)</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-12-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>WY Government hospitals = (21, 24)
WY Private hospitals = (1, 24)
WY Proprietary hospitals = (4, 24)</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-12-output-6.png" class="img-fluid"></p>
</div>
</div>
<p>While the distribution of California hospitals is roughly similar to the distribution of hospitals within the entire U.S., there is a notable lack of private hospitals within Wyoming.</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'All U.S. Hospital Ratings Mean: '</span>, hospital_df[<span class="st">'Rating.Overall'</span>].mean())</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'All U.S. Hospital Ratings Median: '</span>,hospital_df[<span class="st">'Rating.Overall'</span>].median())</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'All U.S. Hospital Ratings Mode: '</span>,hospital_df[<span class="st">'Rating.Overall'</span>].mode())</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>hospital_df.plot(y <span class="op">=</span> <span class="st">'Rating.Overall'</span>, kind <span class="op">=</span> <span class="st">'hist'</span>, bins <span class="op">=</span> <span class="dv">6</span>, color <span class="op">=</span> <span class="st">'purple'</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Rating'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'U.S. Hospitals Overall Ratings (out of 5)'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>plt.show()<span class="op">;</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA Hospital Ratings Mean: '</span>,CAdf[<span class="st">'Rating.Overall'</span>].mean())</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA Hospital Ratings Median: '</span>,CAdf[<span class="st">'Rating.Overall'</span>].median())</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA Hospital Ratings Mode: '</span>,CAdf[<span class="st">'Rating.Overall'</span>].mode())</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>CAdf.plot(y <span class="op">=</span> <span class="st">'Rating.Overall'</span>, kind <span class="op">=</span> <span class="st">'hist'</span>, bins <span class="op">=</span> <span class="dv">6</span>, color <span class="op">=</span> <span class="st">'darkorange'</span>)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Rating'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'CA Hospitals Overall Ratings (out of 5)'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>plt.show()<span class="op">;</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY Hospital Ratings Mean: '</span>,WYdf[<span class="st">'Rating.Overall'</span>].mean())</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY Hospital Ratings Median: '</span>,WYdf[<span class="st">'Rating.Overall'</span>].median())</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY Hospital Ratings Mode: '</span>,WYdf[<span class="st">'Rating.Overall'</span>].mode())</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>WYdf.plot(y <span class="op">=</span> <span class="st">'Rating.Overall'</span>, kind <span class="op">=</span> <span class="st">'hist'</span>, bins <span class="op">=</span> <span class="dv">6</span>, color <span class="op">=</span> <span class="st">'dodgerblue'</span>)</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Rating'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'WY Hospitals Overall Ratings (out of 5)'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>plt.show()<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>All U.S. Hospital Ratings Mean:  2.179379715004191
All U.S. Hospital Ratings Median:  3.0
All U.S. Hospital Ratings Mode:  0    3
Name: Rating.Overall, dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-13-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>CA Hospital Ratings Mean:  2.364705882352941
CA Hospital Ratings Median:  3.0
CA Hospital Ratings Mode:  0    2
Name: Rating.Overall, dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-13-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>WY Hospital Ratings Mean:  1.7857142857142858
WY Hospital Ratings Median:  3.0
WY Hospital Ratings Mode:  0   -1
Name: Rating.Overall, dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-13-output-6.png" class="img-fluid"></p>
</div>
</div>
<p>The “Rating.Overall” column of the dataset is scored on a scale from 1 to 5. However, -1 was used as a placeholder where entries were missing. Thus it will be necessary to remove these null entries to gain a more accurate picture of the data. (See final visualizations and results sections.)</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA Hospital Heart Attack Procedure Mean Cost: '</span>,CAdf[<span class="st">'Procedure.Heart Attack.Cost'</span>].mean())</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA Hospital Heart Attack Procedure Median Cost: '</span>,CAdf[<span class="st">'Procedure.Heart Attack.Cost'</span>].median())</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>CAdf.plot(y <span class="op">=</span> <span class="st">'Procedure.Heart Attack.Cost'</span>, kind <span class="op">=</span> <span class="st">'box'</span>, color<span class="op">=</span><span class="st">'darkorange'</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Cost (USD)'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Heart Attack Procedure Costs in CA'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>plt.show()<span class="op">;</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA Hospital Heart Failure Procedure Mean Cost: '</span>,CAdf[<span class="st">'Procedure.Heart Failure.Cost'</span>].mean())</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA Hospital Heart Failure Procedure Median Cost: '</span>,CAdf[<span class="st">'Procedure.Heart Failure.Cost'</span>].median())</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>CAdf.plot(y <span class="op">=</span> <span class="st">'Procedure.Heart Failure.Cost'</span>, kind <span class="op">=</span> <span class="st">'box'</span>,color<span class="op">=</span><span class="st">'darkorange'</span>)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Cost (USD)'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Heart Failure Procedure Costs in CA'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>plt.show()<span class="op">;</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA Hospital Pneumonia Procedure Mean Cost: '</span>,CAdf[<span class="st">'Procedure.Pneumonia.Cost'</span>].mean())</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA Hospital Pneumonia Procedure Median Cost: '</span>,CAdf[<span class="st">'Procedure.Pneumonia.Cost'</span>].median())</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>CAdf.plot(y <span class="op">=</span> <span class="st">'Procedure.Pneumonia.Cost'</span>, kind <span class="op">=</span> <span class="st">'box'</span>,color<span class="op">=</span><span class="st">'darkorange'</span>)</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Cost (USD)'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Pneumonia Procedure Costs in CA'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>plt.show()<span class="op">;</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA Hospital Hip and Knee Procedures Mean Cost: '</span>,CAdf[<span class="st">'Procedure.Hip Knee.Cost'</span>].mean())</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA Hospital Hip and Knee Procedures Median Cost: '</span>,CAdf[<span class="st">'Procedure.Hip Knee.Cost'</span>].median())</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>CAdf.plot(y <span class="op">=</span> <span class="st">'Procedure.Hip Knee.Cost'</span>, kind <span class="op">=</span> <span class="st">'box'</span>,color<span class="op">=</span><span class="st">'darkorange'</span>)</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Cost (USD)'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Hip and Knee Procedure Costs in CA'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>plt.show()<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CA Hospital Heart Attack Procedure Mean Cost:  14079.597058823529
CA Hospital Heart Attack Procedure Median Cost:  22592.5</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-14-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>CA Hospital Heart Failure Procedure Mean Cost:  12567.961764705882
CA Hospital Heart Failure Procedure Median Cost:  16495.5</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-14-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>CA Hospital Pneumonia Procedure Mean Cost:  15012.9
CA Hospital Pneumonia Procedure Median Cost:  17407.0</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-14-output-6.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>CA Hospital Hip and Knee Procedures Mean Cost:  12629.926470588236
CA Hospital Hip and Knee Procedures Median Cost:  19025.0</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-14-output-8.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY Hospital Heart Attack Procedure Mean Cost: '</span>,WYdf[<span class="st">'Procedure.Heart Attack.Cost'</span>].mean())</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY Hospital Heart Attack Procedure Median Cost: '</span>,WYdf[<span class="st">'Procedure.Heart Attack.Cost'</span>].median())</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>WYdf.plot(y <span class="op">=</span> <span class="st">'Procedure.Heart Attack.Cost'</span>, kind <span class="op">=</span> <span class="st">'box'</span>, color<span class="op">=</span><span class="st">'dodgerblue'</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Cost (USD)'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Heart Attack Procedure Costs in WY'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>plt.show()<span class="op">;</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY Hospital Heart Failure Procedure Mean Cost: '</span>,WYdf[<span class="st">'Procedure.Heart Failure.Cost'</span>].mean())</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY Hospital Heart Failure Procedure Median Cost: '</span>,WYdf[<span class="st">'Procedure.Heart Failure.Cost'</span>].median())</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>WYdf.plot(y <span class="op">=</span> <span class="st">'Procedure.Heart Failure.Cost'</span>, kind <span class="op">=</span> <span class="st">'box'</span>,color<span class="op">=</span><span class="st">'dodgerblue'</span>)</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Cost (USD)'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Heart Failure Procedure Costs in WY'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>plt.show()<span class="op">;</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY Hospital Pneumonia Procedure Mean Cost: '</span>,WYdf[<span class="st">'Procedure.Pneumonia.Cost'</span>].mean())</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY Hospital Pneumonia Procedure Median Cost: '</span>,WYdf[<span class="st">'Procedure.Pneumonia.Cost'</span>].median())</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>WYdf.plot(y <span class="op">=</span> <span class="st">'Procedure.Pneumonia.Cost'</span>, kind <span class="op">=</span> <span class="st">'box'</span>,color<span class="op">=</span><span class="st">'dodgerblue'</span>)</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Cost (USD)'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Pneumonia Procedure Costs in WY'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>plt.show()<span class="op">;</span></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY Hospital Hip and Knee Procedures Mean Cost: '</span>,WYdf[<span class="st">'Procedure.Hip Knee.Cost'</span>].mean())</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY Hospital Hip and Knee Procedures Median Cost: '</span>,WYdf[<span class="st">'Procedure.Hip Knee.Cost'</span>].median())</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>WYdf.plot(y <span class="op">=</span> <span class="st">'Procedure.Hip Knee.Cost'</span>, kind <span class="op">=</span> <span class="st">'box'</span>,color<span class="op">=</span><span class="st">'dodgerblue'</span>)</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Cost (USD)'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Hip and Knee Procedure Costs in WY'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>plt.show()<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>WY Hospital Heart Attack Procedure Mean Cost:  3348.3928571428573
WY Hospital Heart Attack Procedure Median Cost:  0.0</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-15-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>WY Hospital Heart Failure Procedure Mean Cost:  10061.607142857143
WY Hospital Heart Failure Procedure Median Cost:  14711.0</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-15-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>WY Hospital Pneumonia Procedure Mean Cost:  10966.285714285714
WY Hospital Pneumonia Procedure Median Cost:  14957.0</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-15-output-6.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>WY Hospital Hip and Knee Procedures Mean Cost:  10324.82142857143
WY Hospital Hip and Knee Procedures Median Cost:  9077.0</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-15-output-8.png" class="img-fluid"></p>
</div>
</div>
<p>There are very few records for heart attack procedure costs in Wyoming, resulting in a flat boxplot with just a few outliers.</p>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#extracting data for California mortality rates</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="co">#number of hospitals below the national mortality rate</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>CAmortb <span class="op">=</span> CAdf.loc[ CAdf[<span class="st">'Rating.Mortality'</span>] <span class="op">==</span> <span class="st">'Below'</span> ]</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>CAmortb.shape</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co">#number of hospitals the same as the national mortality rate</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>CAmorts <span class="op">=</span> CAdf.loc[ CAdf[<span class="st">'Rating.Mortality'</span>] <span class="op">==</span> <span class="st">'Same'</span> ]</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>CAmorts.shape</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="co">#number of hospitals above the national mortality rate</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>CAmorta <span class="op">=</span> CAdf.loc[ CAdf[<span class="st">'Rating.Mortality'</span>] <span class="op">==</span> <span class="st">'Above'</span> ]</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>CAmorta.shape</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA hospitals below avg mortality ='</span>, CAmortb.shape) </span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA hospitals same as avg mortality ='</span> ,CAmorts.shape) </span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA hospitals above avg mortality ='</span>, CAmorta.shape)</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>CAmx <span class="op">=</span> (<span class="st">'Below'</span>, <span class="st">'Same'</span>, <span class="st">'Above'</span>)</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>CAmy <span class="op">=</span> (<span class="dv">23</span>, <span class="dv">172</span>, <span class="dv">55</span>)</span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>plt.bar(CAmx, CAmy, color <span class="op">=</span> <span class="st">'darkorange'</span>)</span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Rate of Mortality (compared to national average)"</span>, size<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Count of Hospitals"</span>,size<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Mortality Rates in California Hospitals"</span>,size<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a><span class="co">#extracting data for Wyoming mortality rates</span></span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a><span class="co">#number of hospitals below the national mortality rate</span></span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a>WYmortb <span class="op">=</span> WYdf.loc[ WYdf[<span class="st">'Rating.Mortality'</span>] <span class="op">==</span> <span class="st">'Below'</span> ]</span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a>WYmortb.shape</span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-34"><a href="#cb30-34" aria-hidden="true" tabindex="-1"></a><span class="co">#number of hospitals the same as the national mortality rate</span></span>
<span id="cb30-35"><a href="#cb30-35" aria-hidden="true" tabindex="-1"></a>WYmorts <span class="op">=</span> WYdf.loc[ WYdf[<span class="st">'Rating.Mortality'</span>] <span class="op">==</span> <span class="st">'Same'</span> ]</span>
<span id="cb30-36"><a href="#cb30-36" aria-hidden="true" tabindex="-1"></a>WYmorts.shape</span>
<span id="cb30-37"><a href="#cb30-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-38"><a href="#cb30-38" aria-hidden="true" tabindex="-1"></a><span class="co">#number of hospitals above the national mortality rate</span></span>
<span id="cb30-39"><a href="#cb30-39" aria-hidden="true" tabindex="-1"></a>WYmorta <span class="op">=</span> WYdf.loc[ WYdf[<span class="st">'Rating.Mortality'</span>] <span class="op">==</span> <span class="st">'Above'</span> ]</span>
<span id="cb30-40"><a href="#cb30-40" aria-hidden="true" tabindex="-1"></a>WYmorta.shape</span>
<span id="cb30-41"><a href="#cb30-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-42"><a href="#cb30-42" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY hospitals below avg mortality ='</span>, WYmortb.shape) </span>
<span id="cb30-43"><a href="#cb30-43" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY hospitals same as avg mortality ='</span> ,WYmorts.shape) </span>
<span id="cb30-44"><a href="#cb30-44" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY hospitals above avg mortality ='</span>, WYmorta.shape)</span>
<span id="cb30-45"><a href="#cb30-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-46"><a href="#cb30-46" aria-hidden="true" tabindex="-1"></a>WYmx <span class="op">=</span> (<span class="st">'Below'</span>, <span class="st">'Same'</span>, <span class="st">'Above'</span>)</span>
<span id="cb30-47"><a href="#cb30-47" aria-hidden="true" tabindex="-1"></a>WYmy <span class="op">=</span> (<span class="dv">1</span>, <span class="dv">17</span>, <span class="dv">0</span>)</span>
<span id="cb30-48"><a href="#cb30-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-49"><a href="#cb30-49" aria-hidden="true" tabindex="-1"></a>plt.bar(WYmx, WYmy, color <span class="op">=</span> <span class="st">'dodgerblue'</span>)</span>
<span id="cb30-50"><a href="#cb30-50" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Rate of Mortality (compared to national average)"</span>, size<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb30-51"><a href="#cb30-51" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Count of Hospitals"</span>,size<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb30-52"><a href="#cb30-52" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Mortality Rates in Wyoming Hospitals"</span>,size<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb30-53"><a href="#cb30-53" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CA hospitals below avg mortality = (23, 24)
CA hospitals same as avg mortality = (172, 24)
CA hospitals above avg mortality = (55, 24)</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-16-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>WY hospitals below avg mortality = (1, 24)
WY hospitals same as avg mortality = (17, 24)
WY hospitals above avg mortality = (0, 24)</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-16-output-4.png" class="img-fluid"></p>
</div>
</div>
<p>Both states have mortality rates that are mostly the same as the national average. The most important difference that is apparent in these bar charts is that California has roughly 50 hospitals that have mortality rates ABOVE the national average, whereas Wyoming has 0.</p>
<p><strong>Data Analysis</strong></p>
<p>Visualizations List:</p>
<ol type="1">
<li>hospital ratings with null records removed (below)</li>
<li>relationship between the rating and the Pneumonia procedure cost in CA Hospitals (below; I am planning to also add the other procedures)</li>
<li>cost comparisons (boxplots with corresponding CA and WY plots on the same graphs)</li>
<li>comparative boxplots of procedure costs divided by type of hospital within each state (using dataframes created above)</li>
<li>(potentially) a map with the locations of the hospitals within the two states</li>
</ol>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#hospital ratings visualization with null records removed</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>truncated_hdata <span class="op">=</span> hospital_df.loc[hospital_df[<span class="st">'Rating.Overall'</span>] <span class="op">&gt;</span> <span class="fl">0.0</span>]</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'All U.S. Hospital Ratings Mean: '</span>,truncated_hdata[<span class="st">'Rating.Overall'</span>].mean())</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'All U.S. Hospital Ratings Median: '</span>,truncated_hdata[<span class="st">'Rating.Overall'</span>].median())</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'All U.S. Hospital Ratings Mode: '</span>,truncated_hdata[<span class="st">'Rating.Overall'</span>].mode())</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>truncated_hdata.plot(y <span class="op">=</span> <span class="st">'Rating.Overall'</span>, kind <span class="op">=</span> <span class="st">'hist'</span>, bins <span class="op">=</span> <span class="dv">5</span>, color <span class="op">=</span> <span class="st">'purple'</span>)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Rating'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'U.S. Hospitals Overall Ratings (out of 5)'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>plt.show()<span class="op">;</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>truncated_CArat <span class="op">=</span> CAdf.loc[CAdf[<span class="st">'Rating.Overall'</span>] <span class="op">&gt;</span> <span class="fl">0.0</span>]</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA Hospital Ratings Mean: '</span>,truncated_CArat[<span class="st">'Rating.Overall'</span>].mean())</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA Hospital Ratings Median: '</span>,truncated_CArat[<span class="st">'Rating.Overall'</span>].median())</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'CA Hospital Ratings Mode: '</span>,truncated_CArat[<span class="st">'Rating.Overall'</span>].mode())</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>truncated_CArat.plot(y <span class="op">=</span> <span class="st">'Rating.Overall'</span>, kind <span class="op">=</span> <span class="st">'hist'</span>, bins <span class="op">=</span> <span class="dv">5</span>, color <span class="op">=</span> <span class="st">'darkorange'</span>)</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Rating'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'CA Hospitals Overall Ratings (out of 5)'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>plt.show()<span class="op">;</span></span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>truncated_WYrat <span class="op">=</span> WYdf.loc[WYdf[<span class="st">'Rating.Overall'</span>] <span class="op">&gt;</span> <span class="fl">0.0</span>]</span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY Hospital Ratings Mean: '</span>,truncated_WYrat[<span class="st">'Rating.Overall'</span>].mean())</span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY Hospital Ratings Median: '</span>,truncated_WYrat[<span class="st">'Rating.Overall'</span>].median())</span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'WY Hospital Ratings Mode: '</span>,truncated_WYrat[<span class="st">'Rating.Overall'</span>].mode())</span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a>truncated_WYrat.plot(y <span class="op">=</span> <span class="st">'Rating.Overall'</span>, kind <span class="op">=</span> <span class="st">'hist'</span>, bins <span class="op">=</span> <span class="dv">5</span>, color <span class="op">=</span> <span class="st">'dodgerblue'</span>)</span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Rating'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'WY Hospitals Overall Ratings (out of 5)'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a>plt.show()<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>All U.S. Hospital Ratings Mean:  3.0839838492597575
All U.S. Hospital Ratings Median:  3.0
All U.S. Hospital Ratings Mode:  0    3
Name: Rating.Overall, dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-17-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>CA Hospital Ratings Mean:  2.864864864864865
CA Hospital Ratings Median:  3.0
CA Hospital Ratings Mode:  0    2
Name: Rating.Overall, dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-17-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>WY Hospital Ratings Mean:  3.3333333333333335
WY Hospital Ratings Median:  3.0
WY Hospital Ratings Mode:  0    3
Name: Rating.Overall, dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-17-output-6.png" class="img-fluid"></p>
</div>
</div>
<p>Wyoming has no ratings of three.</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>truncated_CArat.plot(y<span class="op">=</span> <span class="st">'Rating.Overall'</span>,x <span class="op">=</span> <span class="st">'Procedure.Hip Knee.Cost'</span>, kind<span class="op">=</span><span class="st">'scatter'</span>, color <span class="op">=</span> <span class="st">'darkorange'</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Rating'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Cost (USD)'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Relationship Between Rating and Hip/Knee Procedure Cost in CA Hospitals'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>plt.show()<span class="op">;</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>truncated_CArat.plot(y<span class="op">=</span> <span class="st">'Rating.Overall'</span>,x <span class="op">=</span> <span class="st">'Procedure.Pneumonia.Cost'</span>, kind<span class="op">=</span><span class="st">'scatter'</span>, color <span class="op">=</span> <span class="st">'darkorange'</span>)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Rating'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Cost (USD)'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Relationship Between Rating and Pneumonia Procedure Cost in CA Hospitals'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>plt.show()<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-18-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-18-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>truncated_WYrat.plot(y <span class="op">=</span> <span class="st">'Rating.Overall'</span>,x <span class="op">=</span> <span class="st">'Procedure.Hip Knee.Cost'</span>, kind<span class="op">=</span><span class="st">'scatter'</span>, color <span class="op">=</span> <span class="st">'dodgerblue'</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Rating'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Cost (USD)'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Relationship Between Rating and Hip/Knee Procedure Cost in WY Hospitals'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>plt.show()<span class="op">;</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>truncated_WYrat.plot(y <span class="op">=</span> <span class="st">'Rating.Overall'</span>,x <span class="op">=</span> <span class="st">'Procedure.Pneumonia.Cost'</span>, kind<span class="op">=</span><span class="st">'scatter'</span>, color <span class="op">=</span> <span class="st">'dodgerblue'</span>)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Rating'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Cost (USD)'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Relationship Between Rating and Pneumonia Procedure Cost in WY Hospitals'</span>,fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>plt.show()<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-19-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-19-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>It does not appear that there is a correlation between cost and rating of hospitals.</p>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<ul>
<li>connection to research question</li>
<li>relevant and detailed info on how research was conducted –&gt; make reproducible</li>
<li>acknowledge limitations of the approach while also asserting why it waas an appropriate choice (rationale)</li>
<li>potentially cites prior research</li>
<li>describes statistical tests run</li>
<li>acknowledges obstacles</li>
</ul>
<p>In this project, I am assessing patient happiness and the quality of treatment by the rating.</p>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<ul>
<li><p>describe data exploration, findings, visuals</p></li>
<li><p>summarizes and presents findings from data analysis</p></li>
<li><p>bulk of narrative</p></li>
<li><p>healthcare prices extremely different between states</p></li>
<li><p>procedure costs do not appear to differ based on quality of hospital/medical attention</p></li>
</ul>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<ul>
<li><p>what have we learned from the results?</p></li>
<li><p>what does the analysis show and why is it important?</p></li>
<li><p>California (most populous state)</p></li>
<li><p>Wyoming (least populous state)</p></li>
</ul>
<p>greater need in california due to greater population density = higher costs</p>
</section>
<section id="works-cited" class="level2">
<h2 class="anchored" data-anchor-id="works-cited">Works Cited</h2>
<p>https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3540621/</p>
<p>https://www.gallaghermalpractice.com/blog/post/what-are-the-different-types-of-hospitals</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>